[package]
name = "actix-basic-api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.4"
actix-rt = "2.7"
rusqlite = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
ron = "0.8.1"
env_logger = "0.10"
log = "0.4"
actix-cors = "0.6"
